/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountSwitcher: typeof import('./src/components/common/AccountSwitcher.vue')['default']
    DeduplicationFieldsSelector: typeof import('./src/components/DeduplicationFieldsSelector.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTag: typeof import('element-plus/es')['ElTag']
    GroupedSidebar: typeof import('./src/components/common/GroupedSidebar.vue')['default']
    Header: typeof import('./src/components/common/Header.vue')['default']
    IcpFooter: typeof import('./src/components/common/IcpFooter.vue')['default']
    JsonViewer: typeof import('./src/components/common/JsonViewer.vue')['default']
    NotificationBell: typeof import('./src/components/common/NotificationBell.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/common/Sidebar.vue')['default']
    SimpleAccountSwitcher: typeof import('./src/components/common/SimpleAccountSwitcher.vue')['default']
    SimpleHeader: typeof import('./src/components/common/SimpleHeader.vue')['default']
    SimpleSidebar: typeof import('./src/components/common/SimpleSidebar.vue')['default']
    UnderDevelopment: typeof import('./src/components/common/UnderDevelopment.vue')['default']
    VerificationResumeDialog: typeof import('./src/components/verification/VerificationResumeDialog.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
