#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Unified star schema ORM (SQLAlchemy) for ERP database.

Tables:
- dim_platforms
- dim_shops
- dim_products
- dim_currency_rates
- fact_orders
- fact_order_items
- fact_product_metrics
- catalog_files (ingestion authority)

Primary keys (confirmed):
- Orders: (platform_code, shop_id, order_id)
- Products: (platform_code, shop_id, platform_sku)
- Metrics: (platform_code, shop_id, platform_sku, metric_date, metric_type)

Notes:
- Keep original currency columns and *_rmb columns.
- Index for (platform_code, shop_id, date/granularity) as critical queries.
- Platform code canonicalization will be handled by ingestion layer; schema stores canonical code.
"""

from __future__ import annotations

from sqlalchemy import JSON as _JSON
from sqlalchemy.dialects.postgresql import JSONB as _JSONB
from sqlalchemy.orm import declarative_base

Base = declarative_base()
JSON_COMPAT = _JSON().with_variant(_JSONB, "postgresql")

from .schema_parts.dimensions import (
    DimPlatform,
    DimShop,
    DimProduct,
    DimProductMaster,
    BridgeProductKeys,
    DimExchangeRate,
    AccountAlias,
    DimCurrencyRate,
)
from .schema_parts.facts import (
    FactOrderAmount,
    FactProductMetric,
    FactTraffic,
    FactService,
    FactAnalytics,
    CatalogFile,
)
from .schema_parts.collection import (
    CollectionConfig,
    CollectionConfigShopScope,
    CollectionConfigRun,
    CollectionTask,
    CollectionTaskLog,
    CollectionSyncPoint,
    TaskCenterTask,
    TaskCenterLog,
    TaskCenterLink,
    EmployeeTask,
    EmployeeTaskLog,
    EmployeeTaskParticipant,
    ApprovalTemplate,
    ApprovalInstance,
    ApprovalStep,
    ApprovalActionLog,
    TrainingProgram,
    TrainingFeishuConfig,
    TrainingAssignment,
    TrainingResult,
    CloudBClassSyncCheckpoint,
    CloudBClassSyncRun,
    CloudBClassSyncTask,
    RefreshQueueTask,
    ComponentVersion,
    ComponentTestHistory,
)
from .schema_parts.platform import (
    Account,
    PlatformAccount,
    MainAccount,
    ShopAccount,
    ShopAccountAlias,
    ShopAccountCapability,
    PlatformShopDiscovery,
)
from .schema_parts.data_platform import (
    DataQuarantine,
    DataFile,
    DataRecord,
    FieldMapping,
    MappingSession,
    StagingOrders,
    StagingProductMetrics,
    StagingInventory,
    ProductImage,
    FieldMappingDictionary,
    FieldMappingTemplate,
    FieldMappingTemplateItem,
    FieldMappingAudit,
    FieldUsageTracking,
    SyncProgressTask,
    EntityAlias,
    StagingRawData,
)
from .schema_parts.business import (
    DimMetricFormula,
    DimCurrency,
    FxRate,
    DimFiscalCalendar,
    DimVendor,
    POHeader,
    POLine,
    GRNHeader,
    GRNLine,
    InventoryLedger,
    InvoiceHeader,
    InvoiceLine,
    InvoiceAttachment,
    ThreeWayMatchLog,
    FactExpensesMonth,
    AllocationRule,
    FactExpensesAllocated,
    LogisticsCost,
    LogisticsAllocationRule,
    TaxVoucher,
    TaxReport,
    GLAccount,
    JournalEntry,
    JournalEntryLine,
    OpeningBalance,
    InventoryLayer,
    InventoryLayerConsumption,
    InventoryAdjustmentHeader,
    InventoryAdjustmentLine,
    ApprovalLog,
    ShopProfitBasis,
    FollowInvestment,
    FollowInvestmentSettlement,
    FollowInvestmentDetail,
    MonthlyProfitSettlement,
    MonthlyProfitPersonnelDetail,
    MonthlyProfitFollowDetail,
    MonthlyProfitAdjustment,
    MonthlyProfitShopBasisSnapshot,
    MonthlyProfitEmployeeCommissionSnapshot,
    MonthlyProfitEmployeePerformanceSnapshot,
    MonthlyProfitPayrollSnapshot,
    ReturnOrder,
    SalesCampaign,
    SalesCampaignShop,
    SalesTarget,
    TargetBreakdown,
    ShopHealthScore,
    ShopAlert,
    PerformanceScore,
    PerformanceConfig,
    ClearanceRanking,
    MaterializedViewRefreshLog,
    DimUser,
    DimRole,
    UserSession,
    UserApprovalLog,
    FactAuditLog,
    SalesTargetA,
    SalesCampaignA,
    OperatingCost,
    Department,
    Position,
    Employee,
    EmployeeTarget,
    EmployeeShopAssignment,
    ShopCommissionConfig,
    EmployeePerformanceAdjustment,
    WorkShift,
    AttendanceRecord,
    LeaveType,
    LeaveRecord,
    OvertimeRecord,
    SalaryStructure,
    PayrollRecord,
    SocialInsuranceConfig,
    PerformanceConfigA,
    EmployeePerformance,
    EmployeeCommission,
    ShopCommission,
    Notification,
    UserNotificationPreference,
    DimRateLimitConfig,
    FactRateLimitConfigAudit,
    SystemLog,
    SecurityConfig,
    BackupRecord,
    SMTPConfig,
    NotificationTemplate,
    AlertRule,
    SystemConfig,
    user_roles,
)

_DIMENSION_EXPORTS = (
    "DimPlatform",
    "DimShop",
    "DimProduct",
    "DimProductMaster",
    "BridgeProductKeys",
    "DimExchangeRate",
    "AccountAlias",
    "DimCurrencyRate",
)
_FACT_EXPORTS = (
    "FactOrderAmount",
    "FactProductMetric",
    "FactTraffic",
    "FactService",
    "FactAnalytics",
    "CatalogFile",
)
_COLLECTION_EXPORTS = (
    "CollectionConfig",
    "CollectionConfigShopScope",
    "CollectionConfigRun",
    "CollectionTask",
    "CollectionTaskLog",
    "CollectionSyncPoint",
    "TaskCenterTask",
    "TaskCenterLog",
    "TaskCenterLink",
    "EmployeeTask",
    "EmployeeTaskLog",
    "EmployeeTaskParticipant",
    "ApprovalTemplate",
    "ApprovalInstance",
    "ApprovalStep",
    "ApprovalActionLog",
    "TrainingProgram",
    "TrainingFeishuConfig",
    "TrainingAssignment",
    "TrainingResult",
    "CloudBClassSyncCheckpoint",
    "CloudBClassSyncRun",
    "CloudBClassSyncTask",
    "RefreshQueueTask",
    "ComponentVersion",
    "ComponentTestHistory",
)
_PLATFORM_EXPORTS = (
    "Account",
    "PlatformAccount",
    "MainAccount",
    "ShopAccount",
    "ShopAccountAlias",
    "ShopAccountCapability",
    "PlatformShopDiscovery",
)
_DATA_PLATFORM_EXPORTS = (
    "DataQuarantine",
    "DataFile",
    "DataRecord",
    "FieldMapping",
    "MappingSession",
    "StagingOrders",
    "StagingProductMetrics",
    "StagingInventory",
    "ProductImage",
    "FieldMappingDictionary",
    "FieldMappingTemplate",
    "FieldMappingTemplateItem",
    "FieldMappingAudit",
    "FieldUsageTracking",
    "SyncProgressTask",
    "EntityAlias",
    "StagingRawData",
)
_BUSINESS_EXPORTS = (
    "DimMetricFormula",
    "DimCurrency",
    "FxRate",
    "DimFiscalCalendar",
    "DimVendor",
    "POHeader",
    "POLine",
    "GRNHeader",
    "GRNLine",
    "InventoryLedger",
    "InvoiceHeader",
    "InvoiceLine",
    "InvoiceAttachment",
    "ThreeWayMatchLog",
    "FactExpensesMonth",
    "AllocationRule",
    "FactExpensesAllocated",
    "LogisticsCost",
    "LogisticsAllocationRule",
    "TaxVoucher",
    "TaxReport",
    "GLAccount",
    "JournalEntry",
    "JournalEntryLine",
    "OpeningBalance",
    "InventoryLayer",
    "InventoryLayerConsumption",
    "InventoryAdjustmentHeader",
    "InventoryAdjustmentLine",
    "ApprovalLog",
    "ShopProfitBasis",
    "FollowInvestment",
    "FollowInvestmentSettlement",
    "FollowInvestmentDetail",
    "MonthlyProfitSettlement",
    "MonthlyProfitPersonnelDetail",
    "MonthlyProfitFollowDetail",
    "MonthlyProfitAdjustment",
    "MonthlyProfitShopBasisSnapshot",
    "MonthlyProfitEmployeeCommissionSnapshot",
    "MonthlyProfitEmployeePerformanceSnapshot",
    "MonthlyProfitPayrollSnapshot",
    "ReturnOrder",
    "SalesCampaign",
    "SalesCampaignShop",
    "SalesTarget",
    "TargetBreakdown",
    "ShopHealthScore",
    "ShopAlert",
    "PerformanceScore",
    "PerformanceConfig",
    "ClearanceRanking",
    "MaterializedViewRefreshLog",
    "DimUser",
    "DimRole",
    "UserSession",
    "UserApprovalLog",
    "FactAuditLog",
    "SalesTargetA",
    "SalesCampaignA",
    "OperatingCost",
    "Department",
    "Position",
    "Employee",
    "EmployeeTarget",
    "EmployeeShopAssignment",
    "ShopCommissionConfig",
    "EmployeePerformanceAdjustment",
    "WorkShift",
    "AttendanceRecord",
    "LeaveType",
    "LeaveRecord",
    "OvertimeRecord",
    "SalaryStructure",
    "PayrollRecord",
    "SocialInsuranceConfig",
    "PerformanceConfigA",
    "EmployeePerformance",
    "EmployeeCommission",
    "ShopCommission",
    "Notification",
    "UserNotificationPreference",
    "DimRateLimitConfig",
    "FactRateLimitConfigAudit",
    "SystemLog",
    "SecurityConfig",
    "BackupRecord",
    "SMTPConfig",
    "NotificationTemplate",
    "AlertRule",
    "SystemConfig",
    "user_roles",
)

__all__ = (
    "Base",
    "JSON_COMPAT",
    *_DIMENSION_EXPORTS,
    *_FACT_EXPORTS,
    *_COLLECTION_EXPORTS,
    *_PLATFORM_EXPORTS,
    *_DATA_PLATFORM_EXPORTS,
    *_BUSINESS_EXPORTS,
)
